### ISSUE TITLE
Missing PortalProg initialization

### ISSUE THREAD

**Issue by FazerJoe** [glatigny/guipro#16]
"events" is not initialized in PortalProg constructor which may lead to unwanted operation.
In my case, with project configuration exemple, "\<quit\/\>" item was executed on start...

Patch needed (v1.5.2):
![image](https://user-images.githubusercontent.com/17196492/57807702-fc4dc900-7761-11e9-9a15-6ac81e935e61.png)

**Comment by obsidev** [comment]
Hi and thanks for the report !
The patch has been added and I generated a new installer for the 1.5.2 release
(I'll see to change the tag afterwards).

**Comment by glatigny** [comment]
Hello and thank you for the report !

The patch has been commit and I have generated a new installer for the 1.5.2 release.
I will adjust the tags later
