### ISSUE TITLE
Enhancement: Internal Definable Variables 

### ISSUE THREAD

**Issue by Shadeclan** [glatigny/guipro#5]
Would it be possible to add the ability to define variables or constants within the XML configuration file that could be used in subsequent XML tags?  I know that your program recognizes a few of the windows system variables but configuration could be simplified if variables could be defined by the user.

**Comment by obsidev** [comment]
Hi,

What kind of variable do you want to define ?
I guess that I could add a special `<variables></variables>` XML tag where you can put some variables, but it can be useful to have some examples in order to be sure that it will handle every cases.

Regards,
J

**Comment by Shadeclan** [comment]
Hi, J.
Suppose I have a particular file location where I have a batch file that launches different programs, depending on the parameter I pass in.  A variable defining that location might be useful when building the configuration file from scratch.  Of course, this probably won't be all that useful once you have the configuration interface done, so I'd consider this a fairly low priority item.

**Comment by obsidev** [comment]
Hi,

The feature as been added in commit https://github.com/obsidev/guipro/commit/2522ab4c63fea0fe7dad67bb456bc2d90963790e
It will be in the next release.

``` XML
<portal>
  <variables>
    <var name="test" value="my test value"/>
    <var name="docs" value="%mydocs%/documents/"/>
  <variables>
  <group>
     <!-- your config where you can use %test% or %docs% -->
  </group>
</portal>
```

Regards,

**Comment by Shadeclan** [comment]
Perfect!  Thanks, J!
