### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Shadeclan** [glatigny/guipro#6]
J,
Putting a percent symbol in the parameters seems to cause PortAL to hang.  Here's a piece of code sure to cause the problem:

`<app name="Windows Explorer" exe="C:\Windows\explorer.exe" param="/e,/root,%L" />`

Work-around is, of course, to use the HTML entity `&percnt;` but I think it shouldn't hang like that.

Good Luck!

**Comment by obsidev** [comment]
Hi,

I made the fix in the source code ; it will be include in the next release.

Regards,
